/*
 * This code was generated by a tool and should not be touched.
 */
namespace FunctionApp.Template.Services.Foo
{
    using System;
    using System.Threading.Tasks;
    using Azure.Messaging.ServiceBus;
    using FakeDomain.Foo.Requests;
    using MediatR.InfrastructureBuilder.Azure.Serverless.Functions;
    using MediatR.InfrastructureBuilder.Serialization;
    using Microsoft.Azure.WebJobs;
    using Microsoft.Azure.WebJobs.Host;
    using Microsoft.Extensions.Logging;

    public class FooService2 : AzureFunctionsDomainServiceBase<FooService2>
    {
        public FooService2(ILogger<FooService2> logger, IMessageDeserializerFactory messageDeserializerFactory)
            : base(logger, messageDeserializerFactory)
        {
        }

        [FunctionName("FooService2_FooRequest2")]
        public Task FooService2_FooRequest2([ServiceBusTrigger(queueName: "foo-request-2-queue", Connection = "")] ServiceBusMessage serviceBusMessage)
        {
            return base.HandleRequestAsync<FooRequest2>(serviceBusMessage);
        }
    }
}
