/*
 * This code was generated by a tool and should not be touched.
 */
namespace FunctionApp.Template.Services.Baz
{
    using System;
    using System.Threading.Tasks;
    using Azure.Messaging.ServiceBus;
    using FakeDomain.Bar.Notifications;
    using FakeDomain.Bar.Requests;
    using FakeDomain.Baz.Requests;
    using FakeDomain.Foo.Notifications;
    using FakeDomain.Foo.Requests;
    using MediatR.InfrastructureBuilder.Azure.Serverless.Functions;
    using MediatR.InfrastructureBuilder.Serialization;
    using Microsoft.Azure.WebJobs;
    using Microsoft.Azure.WebJobs.Host;
    using Microsoft.Extensions.Logging;

    public class BarService1 : AzureFunctionsDomainServiceBase<BarService1>
    {
        public BarService1(ILogger<BarService1> logger, IMessageDeserializerFactory messageDeserializerFactory)
            : base(logger, messageDeserializerFactory)
        {
        }

        [FunctionName("BarService1_FooNotification1")]
        public Task BazService1_FooNotification1([ServiceBusTrigger(topicName: "foo-notification-1-topic", subscriptionName: "foo-notification-1-bar-service-1-subscription", Connection = "")] ServiceBusMessage serviceBusMessage)
        {
            return base.HandleNotificationAsync<FooNotification1>(serviceBusMessage);
        }

        [FunctionName("BarService1_FooNotification2")]
        public Task BazService1_FooNotification2([ServiceBusTrigger(topicName: "foo-notification-2-topic", subscriptionName: "foo-notification-2-bar-service-1-subscription", Connection = "")] ServiceBusMessage serviceBusMessage)
        {
            return base.HandleNotificationAsync<FooNotification2>(serviceBusMessage);
        }

        [FunctionName("BarService1_BarRequest1")]
        public Task BazService1_BazRequest1([ServiceBusTrigger(queueName: "bar-request-1-bar-service-1-topic", Connection = "")] ServiceBusMessage serviceBusMessage)
        {
            return base.HandleRequestAsync<BarRequest1>(serviceBusMessage);
        }

        [FunctionName("BarService1_BarRequest2")]
        public Task BazService1_BazRequest2([ServiceBusTrigger(queueName: "bar-request-2-bar-service-1-topic", Connection = "")] ServiceBusMessage serviceBusMessage)
        {
            return base.HandleRequestAsync<BarRequest2>(serviceBusMessage);
        }
    }
}
