/*
 * This code was generated by a tool and should not be touched.
 */
namespace FunctionApp.Template.Services.Baz
{
    using System;
    using System.Threading.Tasks;
    using Azure.Messaging.ServiceBus;
    using FakeDomain.Bar.Notifications;
    using FakeDomain.Baz.Requests;
    using FakeDomain.Foo.Notifications;
    using FakeDomain.Foo.Requests;
    using MediatR.InfrastructureBuilder.Azure.Serverless.Functions;
    using MediatR.InfrastructureBuilder.Serialization;
    using Microsoft.Azure.WebJobs;
    using Microsoft.Azure.WebJobs.Host;
    using Microsoft.Extensions.Logging;

    public class BazService1 : AzureFunctionsDomainServiceBase<BazService1>
    {
        public BazService1(ILogger<BazService1> logger, IMessageDeserializerFactory messageDeserializerFactory)
            : base(logger, messageDeserializerFactory)
        {
        }

        [FunctionName("BazService1_FooNotification1")]
        public Task BazService1_FooNotification1([ServiceBusTrigger(topicName: "foo-notification-1-topic", subscriptionName: "foo-notification-1-baz-service-1-subscription", Connection = "")] ServiceBusMessage serviceBusMessage)
        {
            return base.HandleNotificationAsync<FooNotification1>(serviceBusMessage);
        }

        [FunctionName("BazService1_FooNotification2")]
        public Task BazService1_FooNotification2([ServiceBusTrigger(topicName: "foo-notification-2-topic", subscriptionName: "foo-notification-2-baz-service-1-subscription", Connection = "")] ServiceBusMessage serviceBusMessage)
        {
            return base.HandleNotificationAsync<FooNotification2>(serviceBusMessage);
        }

        [FunctionName("BazService1_FooNotification3")]
        public Task BazService1_BarNotification3([ServiceBusTrigger(topicName: "foo-notification-3-topic", subscriptionName: "foo-notification-3-baz-service-1-subscription", Connection = "")] ServiceBusMessage serviceBusMessage)
        {
            return base.HandleNotificationAsync<FooNotification3>(serviceBusMessage);
        }

        [FunctionName("BazService1_BarNotification1")]
        public Task BazService1_BarNotification1([ServiceBusTrigger(topicName: "bar-notification-1-topic", subscriptionName: "bar-notification-1-baz-service-1-subscription", Connection = "")] ServiceBusMessage serviceBusMessage)
        {
            return base.HandleNotificationAsync<BarNotification1>(serviceBusMessage);
        }

        [FunctionName("BazService1_BarNotification2")]
        public Task BazService1_BarNotification2([ServiceBusTrigger(topicName: "bar-notification-2-topic", subscriptionName: "bar-notification-2-baz-service-1-subscription", Connection = "")] ServiceBusMessage serviceBusMessage)
        {
            return base.HandleNotificationAsync<BarNotification2>(serviceBusMessage);
        }

        [FunctionName("BazService1_BazRequest1")]
        public Task BazService1_BazRequest1([ServiceBusTrigger(queueName: "baz-request-1-queue", Connection = "")] ServiceBusMessage serviceBusMessage)
        {
            return base.HandleRequestAsync<BazRequest1>(serviceBusMessage);
        }
    }
}
